name: lint

on:
  - push
  - pull_request

jobs:
  lint:
    container: node:12.14.1-buster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn lint
