name: test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: brew install influxdb
      - run: influxd &
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn
      - run: yarn test
